# Generated by Django 2.2 on 2020-07-13 05:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('showsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shows',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
