# Generated by Django 2.2 on 2020-07-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showsManager', '0002_auto_20200713_0536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shows',
            managers=[
            ],
        ),
    ]
